### ISSUE TITLE
Not able to get it work with IE10 browser

### ISSUE THREAD

**Issue by GirishAd** [ngx-translate/core#450] opened 2017-02-28 13:51 UTC
[X ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
TranslateService.use method breaks when accessing the app in IE10. The code breaks when calling translateService.use('selected-lang'); in IE10. When debugged the .use method, I get InvalidStateError in zone.min.js.

**Expected/desired behavior**
It should work with IE10 and set language accordingly.

**Reproduction of the problem**
Could not create proper plnkr for this problem but the plnkr provided on your NPM page is not working in IE10. http://plnkr.co/edit/btpW3l0jr5beJVjohy1Q?p=preview

**What is the expected behavior?**
It should work with IE10 and set language accordingly.

**What is the motivation / use case for changing the behavior?**
Browser compatibility.
 
**Please tell us about your environment:**
Windows 7 + IE 10

* **ngx-translate version:** 5.0.0

* **Angular version:** 2.4.8
 
* **Browser:** [IE 10]

**Comment by SamVerschueren** [comment] 2017-02-28 14:04
Is this correct?

> **ngx-translate version:** 3.1.0

We are currently at 6.0.0. Not sure if the current version works in IE10 though, just wondering if you tried upgrading.

**Comment by GirishAd** [comment] 2017-02-28 15:02
@SamVerschueren Sorry for the confusion. We are actually using v 5.0.0 (latest from npm).

**Comment by richflee** [comment] 2018-01-09 06:38
@GirishAd any luck with resolving this one? I'm not having any luck getting ngx-translate to work on Windows 7 (IE11 or IE10) at the moment. I'm using ngx-core@8.0.0

**Comment by ocombe** [comment] 2018-01-09 08:25
@richflee could you narrow it down to figure out what's breaking? I only have windows 10 here and it works fine on IE11/IE10

**Comment by richflee** [comment] 2018-01-09 09:29
@ocombe Sure. When using getBrowserLang() the language detected is always 'en' despite adding spanish languages (via Internet Options) and making them the top preference. Am I missing something?

**Comment by ocombe** [comment] 2018-01-09 09:34
Can you test the function independently and see where it's failing to get the correct lang?
This is the code of the function:

```ts
    public getBrowserLang(): string {
        if(typeof window === 'undefined' || typeof window.navigator === 'undefined') {
            return undefined;
        }

        let browserLang: any = window.navigator.languages ? window.navigator.languages[0] : null;
        browserLang = browserLang || window.navigator.language || window.navigator.browserLanguage || window.navigator.userLanguage;

        if(browserLang.indexOf('-') !== -1) {
            browserLang = browserLang.split('-')[0];
        }

        if(browserLang.indexOf('_') !== -1) {
            browserLang = browserLang.split('_')[0];
        }

        return browserLang;
    }
```

**Comment by richflee** [comment] 2018-01-15 05:19
@ocombe Cool. I've tested using the function you described. 

`browserLang = browserLang || window.navigator.language || window.navigator['browserLanguage'] || window.navigator['userLanguage'];`
^ This line picks up the language as 'en-AU'

And then finally returns 'en' (after using browserLang.split etc)

Any ideas? Am I missing something?

This is my package.json
`{
  "name": "world-watch",
  "version": "0.0.0",
  "license": "MIT",
  "scripts": {
    "ng": "ng",
    "start": "ng serve",
    "build": "ng build",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },
  "private": true,
  "dependencies": {
    "@angular/animations": "4.4.6",
    "@angular/common": "4.4.6",
    "@angular/compiler": "4.4.6",
    "@angular/core": "4.4.6",
    "@angular/forms": "4.4.6",
    "@angular/http": "4.4.6",
    "@angular/platform-browser": "4.4.6",
    "@angular/platform-browser-dynamic": "4.4.6",
    "@angular/router": "4.4.6",
    "@ngrx/core": "^1.2.0",
    "@ngrx/effects": "^4.1.1",
    "@ngrx/store": "^4.1.1",
    "@ngrx/store-devtools": "^4.1.1",
    "@ngx-translate/core": "^8.0.0",
    "@ngx-translate/http-loader": "^2.0.1",
    "core-js": "^2.4.1",
    "immutable": "^3.8.2",
    "intl": "^1.2.5",
    "rxjs": "^5.4.2",
    "zone.js": "^0.8.14"
  },
  "devDependencies": {
    "@angular/cli": "1.4.9",
    "@angular/compiler-cli": "4.4.6",
    "@angular/language-service": "4.4.6",
    "@types/jasmine": "~2.5.53",
    "@types/jasminewd2": "~2.0.2",
    "@types/node": "~6.0.60",
    "codelyzer": "~3.2.0",
    "jasmine-core": "~2.6.2",
    "jasmine-spec-reporter": "~4.1.0",
    "karma": "~1.7.0",
    "karma-chrome-launcher": "~2.1.1",
    "karma-cli": "~1.0.1",
    "karma-coverage-istanbul-reporter": "^1.2.1",
    "karma-jasmine": "~1.1.0",
    "karma-jasmine-html-reporter": "^0.2.2",
    "protractor": "~5.1.2",
    "ts-node": "~3.2.0",
    "tslint": "~5.7.0",
    "typescript": "2.4.1"
  }
}
`

**Comment by ocombe** [comment] 2018-01-15 08:12
There is no cross browser function that I know of to get the browser complete locale id ("en-AU" instead of "en"), since some old browsers only return the first part, which is why this function only returns "en".

That being said, the issue for you is that it picks up "en-AU" instead of "es-ES" or something like that, right?
I think that IE returns the language from windows instead of the option defined in the browser settings.

**Comment by richflee** [comment] 2018-01-15 08:57
> That being said, the issue for you is that it picks up "en-AU" instead of "es-ES" or something like that, right?

Yes, that's correct.

> I think that IE returns the language from windows instead of the option defined in the browser settings.
Oh okay. If you change the browser defined settings (in IE) and go to other sites like Google, then the webpage does indeed detect the language change from the browser settings. 

From research it does appear that you have to change the OS language on Windows 10. But in my reading so far I haven't seen anything to suggest that you had to change OS language on Windows 7.

**Comment by richflee** [comment] 2018-01-16 08:37
@ocombe Sorry, just to clarify - so is that the expected behavior on Windows 7? That you **have** to change the language of the entire OS in order for the browser to pick up a different language?

**Comment by ocombe** [comment] 2018-01-16 08:51
After a quick search, this post & its comments explain it well: https://stackoverflow.com/a/2678437/649896
- languages (chrome & firefox): list of user-preferred languages (defined by the user in browser; note though that navigator.languages[0] might be totally different than navigator.language)
- language (IE11+ & others: browser install language)
- browserLanguage (IE, browser install language)
- userLanguage (IE, user-level OS-wide language setting)
- systemLanguage (IE, OS installation language)
 
In IE11 navigator.language === navigator.userLanguage. The value of userLanguage can be changed by the user on Windows in Control Panel > Region and Language.
In IE11 you simply cannot reliably determine the most preferred and supported language, you have to resort to your server sending back the Accept-Language header (processed or not).

**Comment by ocombe** [comment] 2018-05-08 12:48
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please open a new issue.

**Closed by ocombe** 2018-05-08 12:48 UTC
