### ISSUE TITLE
'translate' directive not working as expected

### ISSUE THREAD

**Issue by jeanpaulattard** [ngx-translate/core#380] opened 2017-01-02 08:48 UTC
**I'm submitting a ...**  (check one with "x")
```
[x ] bug report => check the FAQ and search github for a similar issue or PR before submitting
```

**Current behavior**

I'm currently using the 'translate' directive in  the following manner (following the examples provided in the readme)

`<strong [translate]="'HELLO'"></strong> (note the single quotes)`

however the innerHTML of the `<strong>` element is not filled. The resultant html is as follows : 

`<strong ng-reflect-translate="REGISTRATION.HEADER"></strong>`

On the other hand, when i use the translate directive like in the following manner 

`<strong translate>HELLO</strong>`

the innerHTML of the `<strong>` element is being filled with the correct translations.

**Expected/desired behavior**

The first method should work like the second method, as described in the readme.

**Please tell us about your environment:**

* **ng2-translate version:** 5.0.0

* **Angular version:** 2.2.4
 
* **Browser:** [Chrome latest] 
 
* **Language:** [ TypeScript 2.0.10 ]

**Comment by kirillgroshkov** [comment] 2017-01-19 14:51
I have the same issue. It works when you do this:

```
<strong [translate]="'HELLO'">any non empty content here</strong>
```

But doesn't work when the content of the node is empty.

**Comment by ocombe** [comment] 2017-02-14 16:28
Duplicate of #355, closing this one

**Closed by ocombe** 2017-02-14 16:28 UTC
Labels: Type: bug
