### ISSUE TITLE
TranslateModule doesn't work when used with webpack

### ISSUE THREAD

**Issue by dackmin** [ngx-translate/core#805] opened 2018-03-05 15:13 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

![capture d ecran 2018-03-05 a 15 54 16](https://user-images.githubusercontent.com/1873323/36981468-813cf2a8-208d-11e8-8912-db4d9f4ebd56.png)

**Expected/desired behavior**

Not having this error 😄 

**Reproduction of the problem**

Using a plunker wasn't quite easy with this issue, so I made a repo : https://github.com/dackmin/ngx-translate-issue
`master` branch : broken project using `@ngx-translate/core@9.1.1`
`working-with-v8` branch : working project using `@ngx-translate/core@8.0.0`

Simply run `yarn install` or `npm install` and `yarn start` or `npm start`

Project is using webpack 4, but the same problem goes with webpack 3.

**What is the expected behavior?**

TranslateModule and TranslateService should be working fine when using either angular-cli or webpack

**What is the motivation / use case for changing the behavior?**

To be able to update `@ngx-translate/core` to the latest version and not being stuck to `v8.0.0` until the end of times.

**Please tell us about your environment:**

* **ngx-translate version:** 9.1.1

* **Angular version:** 5.2.7
 
* **Browser:** All (tested on Chrome 64, Firefox 58, & Safari 11)

**Comment by CodeAndWeb** [comment] 2018-03-29 22:16
Ok - I can reproduce the issue with your demo project.

I've build and almost identical project with TypeScript and it works.

The issue seems to be that the dependency injection can't create the TranslateService.
I am having a hard time writing CoffeeScript... so I can't give you a solution.

What might work is the following: Create a factory that creates the TranslateService and add it to the providers in app.module.coffee. This should at least give you an idea which parameters don't work.

**Comment by dackmin** [comment] 2018-03-30 08:57
Is there a way I can have a look at your TypeScript take on the issue 😄  ?
I will try with the factory move and provide some feedback as soon as I can.

**Comment by dackmin** [comment] 2018-03-30 10:31
I used Chrome debugger to try to understand what is going on with TranslateService parameters, and just for informational purposes this is what I got with working `@ngx-translate/core@8.x.x` :

![capture d ecran 2018-03-30 a 12 13 31](https://user-images.githubusercontent.com/1873323/38134787-efbe1ece-3414-11e8-899b-caacc0291547.png)

And with non-working `ngx-translate/core@9.x.x` : 

![capture d ecran 2018-03-30 a 12 16 45](https://user-images.githubusercontent.com/1873323/38134896-71774210-3415-11e8-8be9-6ce9d10b71d2.png)

If you don't use `core.umd.js` or `core.es5.js` when using typescript (I'm not very familiar with typescript, as you may have noticed) the problem is probably with any of those two files.

If I'm not mistaking, making a full ES5/6 only project should throw the exact same error.
Will try that on another branch of my issue repository.

**Comment by CodeAndWeb** [comment] 2018-03-30 10:38
The code is here: https://github.com/CodeAndWeb/ngx-translate-demo in the ngx-translate-demo folder.

I was already wondering why the error message is [?,?,?,?,[object],[object]]. I'd not expect to see [object] where a Boolean is required...

This is why I came up with the idea of creating a factory method to manually instantiate TranslationService.

**Comment by CodeAndWeb** [comment] 2018-03-30 10:40
I also saw this on the console... which correlate with the for "?"

```
WARNING in ./node_modules/@angular/core/esm5/core.js
6558:15-36 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./app/index.coffee
 @ multi (webpack)-dev-server/client?http://localhost:9090 webpack/hot/dev-server ./app/index.coffee

WARNING in ./node_modules/@angular/core/esm5/core.js
6578:15-102 Critical dependency: the request of a dependency is an expression
 @ ./node_modules/@angular/core/esm5/core.js
 @ ./app/index.coffee
 @ multi (webpack)-dev-server/client?http://localhost:9090 webpack/hot/dev-server ./app/index.coffee

WARNING in ./node_modules/@angular/core/esm5/core.js
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./app/index.coffee 6558:15-36 9:12-36
 @ multi (webpack)-dev-server/client?http://localhost:9090 webpack/hot/dev-server ./app/index.coffee

WARNING in ./node_modules/@angular/core/esm5/core.js
System.import() is deprecated and will be removed soon. Use import() instead.
For more info visit https://webpack.js.org/guides/code-splitting/
 @ ./app/index.coffee 6578:15-102 9:12-36
 @ multi (webpack)-dev-server/client?http://localhost:9090 webpack/hot/dev-server ./app/index.coffee

```

**Comment by CodeAndWeb** [comment] 2018-03-30 10:48
Google came up with this: https://github.com/angular/angular/issues/20357

**Comment by dackmin** [comment] 2018-03-30 10:49
here you go : https://github.com/dackmin/ngx-translate-issue/tree/non-working-with-es6

Angular core warnings have always been there, using `v8.x.x` or `v9.x.x`. I was going to link you this issue but you already found it :)

**Comment by CodeAndWeb** [comment] 2018-04-04 06:08
I am closing this ticket for now. 
See name issue in #754

**Closed by CodeAndWeb** 2018-04-04 06:08 UTC
Labels: Status: help wanted
