### ISSUE TITLE
Issue: Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function

### ISSUE THREAD

**Issue by narendravyas** [ngx-translate/core#578] opened 2017-06-22 12:34 UTC
Hi All,
I am trying to use the module in my web app but getting following issue again and again. 

**ERROR in Error encountered resolving symbol values statically. Function calls are not supported. Consider replacing the function or lambda with a reference to an exported function (position 59:25 in the original .ts file), resolving symbol AppModule in /opt/lampp/htdocs/.../src/app/app.module.ts**

What I did is : 

In app.module.ts:

import {TranslateModule, TranslateLoader, TranslateStaticLoader} from 'ng2-translate';
imports: [
      TranslateModule.forRoot({
           provide: TranslateLoader,
            useFactory: (http: Http) => new TranslateStaticLoader(http, '/assets/i18n', '.json'),
            deps: [Http]
        }),
] 

When using this way its giving error but using just   TranslateModule.forRoot(); their is not error.

The error that I am getting is when compiling my app using **ng build --aot --prod --output-hashing none**, on simple ng-serve its fine.

* What **I tried** is using this way:
               function httpFactory(http: Http) {
  return new TranslateStaticLoader(http, '/assets/i18n', '.json');
}

TranslateModule.forRoot({
      provide: TranslateLoader,
      useFactory: httpFactory,
      deps: [Http]
    })

as suggested here: https://github.com/angular/angular-cli/issues/4647 , but this is also not working for my case.

**Also tried:**
providers: [ TranslateService, { provide: TranslateLoader, useFactory: translateLoader, deps: [Http] } ]
export function translateLoader(http: Http) { return new TranslateStaticLoader(http, 'assets/i18n', '.json');

On doing this not getting above mentioned error but getting error in console "The pipe 'translate' could not be found". 

Any help please 

Angular cli version:

@angular/cli: 1.0.4
node: 6.10.3
os: linux x64
@angular/common: 4.1.3
@angular/compiler: 4.1.3
@angular/core: 4.1.3
@angular/forms: 4.1.3
@angular/http: 4.1.3
@angular/platform-browser: 4.1.3
@angular/platform-browser-dynamic: 4.1.3
@angular/router: 4.1.3
@angular/cli: 1.0.4
@angular/compiler-cli: 4.1.3

Angular version: 4.1.3

Any help please ??

**Comment by KarolBuchta** [comment] 2017-07-12 11:38
Having the exact same issue with ngc, on ngx-translate 7.0.0. Not specifying a config, just calling TrasnlateModule.forRoot(), with the workaround from the docu it doesn't work as well.

I am using:
    "@angular/compiler": "4.2.6",
    "@angular/compiler-cli": "4.2.6",
    "@ngx-translate/core": "7.0.0",

Still the same error.

Error encountered resolving symbol values statically. Calling function 'TranslateModule', function calls are not supported. Consider replacing the function or lambda with a reference to an exported function, resolving symbol...

**Comment by KarolBuchta** [comment] 2017-07-12 11:48
@narendravyas @leNicDev Was one of you able to fix this with a workaround somehow? I am stuck here, and really don't want to postpone this task.

**Comment by leNicDev** [comment] 2017-07-18 17:15
@KarolBuchta I'm still stuck here too.

**Comment by AnthonyNahas** [comment] 2017-09-12 19:56
this usually happens if the internal npm module contains the dir node_modules too ...

**Comment by wcorderolara** [comment] 2018-02-21 22:15
@ocombe,do you have any idea how resolve this issue?, I got this error when was using ng2-translate and for that reason I switched to ngx-translate, but when try to build  or execute my project appears this error, if I delete the lambda function, all works fine, but don't recognize me the location for the "i18n" directory and just appears the wildcards.

### Error
![ng_translate_build_error](https://user-images.githubusercontent.com/3922920/36508314-622f3d38-172a-11e8-9638-75bc593e76ac.png)

### Template without lambda function
![wildcards_template](https://user-images.githubusercontent.com/3922920/36508442-b906db84-172a-11e8-9944-a01e0c4d642a.png)

**Comment by ocombe** [comment] 2018-05-08 13:39
Hello, I'm closing this issue because it's too old.
If you have a similar problem with recent version of the library, please provide a stackblitz of github repo that I can use to reproduce the error.

**Closed by ocombe** 2018-05-08 13:39 UTC
Labels: Status: Review

**Comment by broweratcognitecdotcom** [comment] 2018-08-29 14:01
Angular 6.1.4
@ngx-translate/core 10.0.2
rxjs 6.2.2

Function calls are not supported in decorators but 'TranslateModule' was called. Please reopen this.
