### ISSUE TITLE
.forChild() usage with lazy loading routes

### ISSUE THREAD

**Issue by dhardtke** [ngx-translate/core#425] opened 2017-02-11 03:15 UTC
**I'm submitting a ...**  (check one with "x")
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
`AppModule`
```typescript
export function createTranslateLoader(http: Http) {
    return new TranslateHttpLoader(http, "/i18n/", "/index.json");
}
imports: [
    TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useFactory: createTranslateLoader,
                deps: [Http]
            }
        }),
]
```
`SharedModule`
```typescript
imports: [
    //TranslateModule
],
exports: [
    //TranslateModule,
]
```

`AdminModule`
```
export function createTranslateLoader(http: Http) {
    return new TranslateHttpLoader(http, "/i18n/", "/admin.json");
}
imports: [
    TranslateModule.forChild({
            loader: {
                provide: TranslateLoader,
                useFactory: createTranslateLoader,
                deps: [Http]
            }
        }),
]
```

**Expected/desired behavior**
I would like to load additional JSON files per component / module, i.e. an admin.json for the administration panel of our app.
I would like to import one TranslateModule inside of `SharedModule` and configure it allow all modules that don't explicite call .forChild().

Both doesn't work, it simply doesn't load the admin.json and hence doesn't translate strings defined in that file.

**Please tell us about your environment:**

* **ngx-translate version:** 6.0.0-beta.1

* **Angular version:** 2.4.7
 
* **Browser:** [Firefox 51.0.1] 
 
* **Language:** [TypeScript 2.0]

**Comment by neolanders** [comment] 2017-02-21 19:47
Since I didn't found any plunker working with ngx-translate librairy and I also add some difficulties to manage to make it work with LoadChildren,
I've setup a way that work pretty well for me:

_I've created two SharedModules, (one for lazyLoading and one for the other part of my application)_

**SharedLazyModule for lazy loading content:**

```
@NgModule({
  imports: [
    HttpModule,
    CommonModule,
    TranslateModule.**forChild**({}),
  ],
  exports: [
    CommonModule,
    TranslateModule
  ]
})
export class SharedLazyModule {}
```


**SahredModule for App**

```
// AoT requires an exported function for factories
export function HttpLoaderFactory(http: Http) {
   return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

@NgModule({
    imports: [
      HttpModule,
      CommonModule,
      TranslateModule.**forRoot**({
           provide: TranslateLoader,
           useFactory: HttpLoaderFactory,
           deps: [Http],
         })
    ],
    exports: [
      CommonModule,
      TranslateModule
    ]
})
export class SharedModule {
    
     constructor(private translate: TranslateService) {
                  
        translate.addLangs(["en", "fr"]);
        translate.setDefaultLang('en');

        let browserLang = translate.getBrowserLang();
        translate.use(browserLang.match(/en|fr/) ? browserLang : 'en');
    }
}
```

See Plunker:
https://plnkr.co/LVmIuI1Xw9vFn0IuC2jW

**Comment by mebibou** [comment] 2017-09-20 12:21
@neolanders your answer does not relate to the question, you are posting the solution explained in the README for SharedModule.
I'm trying to create a module on top of the `TranslateModule` where each module could put in his translations, but so far not successful

**Comment by dhardtke** [comment] 2017-09-20 18:55
I believe ngx-translate is broken in regards to its "Lazy loading feature" and since ocombe is now part of the Angular core team, it will probably never get fixed.

Most likely, people will have to switch to Angular's i18n functionality once it becomes more rich in regards to its features.

**Comment by Tuizi** [comment] 2017-09-23 15:41
I wrote a article about how to have 1 json file per lazy loaded module without having to write a new Custom Loader etc... it's quiet simple, only the documentation is not clear in fact:
https://medium.com/@TuiZ/how-to-split-your-i18n-file-per-lazy-loaded-module-with-ngx-translate-3caef57a738f

**Comment by mebibou** [comment] 2017-09-24 09:01
@Tuizi your solution is a workaround, since you are basically creating `TranslateModule` in every lazy loaded module, and you need something in between to keep the selected lang synced. The problem we are talking about is that it should work without this workaround that we all have to do for now

**Comment by Tuizi** [comment] 2017-09-26 14:01
@mebibou I'm curious about what contributors think about that. For me it's not a workaround has I simply follow what the documentation say (paragraph "lazy loaded module")

**Comment by mebibou** [comment] 2017-09-26 14:05
@Tuizi no I'm saying that's not the point of the issue here. We want to have lazy loading modules being in sync with the master modules, without having to push the changes of `lang` from master to slave everytime. It should basically work without needing to use `isolate: true` and adding some code (your `this.store.dispatch` and all)

**Comment by pieterdegraeuwe** [comment] 2017-10-06 12:44
any progress on this? is Tuizi's solution is indead a work-around. Anyone found a real solution / fix?

**Comment by Tuizi** [comment] 2017-10-06 13:41
What would be a real solution?

I have time to work on a PR and I would like to try to solve this problem, which seems to impact many people.

What do you think of that?

**Core Module**
```typescript
export function createTranslateLoader(http: HttpClient) {
  // We may need a new loader? To define the folder where i18n's files are, and the extension
  return new LazyTranslateHttpLoader(http, './assets/i18n/', '.json');
}

TranslateModule.forRoot({
  loader: {
      provide: TranslateLoader,
      useFactory: (createTranslateLoader),
      deps: [HttpClient]
  }
})
```

**Lazy loaded Module: admin**
```typescript
  TranslateModule.forChild({lazy: 'admin'})
```

When admin module is loaded, the file `./assets/i18n/admin/en.json` will be requested. 

What do you think of that?

**Comment by mebibou** [comment] 2017-10-06 14:07
I wouldn't mind having to create different translateLoader per module, just without using `isolate: true` should work, something along:

```
// app.module.ts
export function HttpLoaderFactory(http: Http) {
   return new TranslateHttpLoader(http, './assets/i18n/app/', '.json');
}

@NgModule({
    imports: [
      TranslateModule.forChild({
        loader: {
          provide: TranslateLoader,
           useFactory: HttpLoaderFactory,
           deps: [Http]
        }
     })
   ]
})
export class AppModule {}

// in a lazy-loaded page's module
// pages/home/page.module.ts
export function HttpLoaderFactory(http: Http) {
   return new TranslateHttpLoader(http, './assets/i18n/home/', '.json');
}

@NgModule({
    imports: [
      TranslateModule.forChild({
        loader: {
          provide: TranslateLoader,
           useFactory: HttpLoaderFactory,
           deps: [Http]
        }
     })
   ]
})
export class HomePageModule {}
```

**Comment by mebibou** [comment] 2017-10-06 14:10
@Tuizi taken from the [README](https://github.com/ngx-translate/core#lazy-loaded-modules):
> Otherwise, by default, it will share its data with other instances of the service (but you can still use a different loader/compiler/parser/handler even if you don't isolate the service).

I don't think that is true, when I don't use `isolate: true`, my custom translate loader (like in example above) does not load the translation at all, nothing happens

**Comment by Tuizi** [comment] 2017-10-06 14:12
Thank you are right. I will check that

**Comment by Almar** [comment] 2017-12-07 15:05
If I understand correctly, the OP wants to lazily load translations along with his lazily loaded modules. We did managed to load translations lazily but used a slightly different approach. All our translations are defined in 'namespaces' and every translation key is prefixed with the namespace (for instance 'validations.required'). Our translations are loaded with a MissingTranslationHandler. The MissingTranslationHandler uses the namespace to determine which translation file to load.

So, we're not lazily loading our translations per (lazily loaded) module but per translation namespace. By prefixing your translation keys with your module name you could of course get the required effect.

[Gist with our MissingTranslationHandler](https://github.com/PowerhouseBV/gists/blob/master/angular/translate/inni-missing-translate-handler.ts)

Hope this can help someone.

**Comment by gate3** [comment] 2017-12-25 13:09
Seems the best thing you can do right now is use namespacing, with the -f namespaced-json flag

**Comment by Mokto** [comment] 2018-03-28 12:33
@Almar Thanks !! That's a great solution for now.

**Comment by Dunos** [comment] 2018-04-03 10:43
@ocombe are you planning to fix/support this any time soon?

**Comment by emmano3h** [comment] 2018-06-12 15:46
I tried forchild solution but it is not working. Could we have any plunk working well ?
ngx-translate version: 6.0.0-beta.1

Angular version: 6.0.3

Browser: [Chrome Version 67.0.3396.79 (Official Build) (64-bit)]

Language: [TypeScript 2.7.2]

**Comment by ocombe** [comment] 2018-06-12 15:48
If you use Angular v6, you have to use ngx translate version >= 10

**Comment by emmano3h** [comment] 2018-06-12 16:03
@ocombe  here my configs:

"@ngx-translate/core": "^10.0.2",
"@ngx-translate/http-loader": "^3.0.1",

**Comment by wilker7ribeiro** [comment] 2018-06-22 20:02
Same here

**Comment by YaroslavLyzlov** [comment] 2018-08-21 07:31
Same here (angular 6.1.3, ngx-translate 10.0.2)

**Comment by erperejildo** [comment] 2018-08-29 12:48
don't get this... do we need to keep `.forChild` and `.forRoot` together? I get an error if I don't add the second one:

> Could not find IonicModule.forRoot call in "imports"

**Comment by cdskill** [comment] 2018-09-14 08:07
Personnaly I still have a issue for getting all my translations... my scenario is : 
a main application calling
    a lazy loaded module
          where is a container module 
                 where the translation is used.
Everything works expect the translation :-/

If I dont lazy load I get my translations.

There is a sample:
`app.module
`

```
// Http loader for ngx-translate.
export function createTranslateLoader(http: HttpClient, settings: GlobalAppSettings) {
  return new TranslationLoader(http, settings);
}

@NgModule({
  declarations: [
....
  ],
  imports: [
....

    // Other external modules.
    TranslateModule.forRoot({
      loader: { provide: TranslateLoader, useFactory: (createTranslateLoader), deps: [HttpClient, GlobalAppSettings] }, isolate: true
....
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }

```


`app-routing.module`



    imports....
    export const routes: Routes = [
    ...
        {
            path: 'unemployment-info',
            canActivate:[OAuthGuardService],
            loadChildren: './unemployment.module#UnemploymentModule',
            data: { id: 4, title:'tabs.eDossier' }
        
        }
    ...
    ];

    @NgModule({
        imports: [RouterModule.forRoot(routes, {preloadingStrategy: PreloadAllModules, enableTracing:false})],
        exports: [RouterModule]
    })
    export class AppRoutingModule { }

`unemployment.module`

    export const routes: Routes = [{ path: '', component: UnemploymentInfoComponent }];
    // Http loader for ngx-translate.
    export function createTranslateLoader(httpClient: HttpClient, settings: GlobalAppSettings) {
      return new TranslationLoader(httpClient, settings);
    }

    @NgModule({
      imports: [
        CommonModule,
        RouterModule.forChild(routes),
        EDossierContainerModule,
        TranslateModule.forChild({
          loader: { provide: TranslateLoader, useFactory: (createTranslateLoader), deps: [HttpClient, 
    GlobalAppSettings] }
        }),
      ], exports: [],
      declarations: [...]
    })
    export class UnemploymentModule { }

`e-dossier-container.module`

```
// Http loader for ngx-translate.
export function createTranslateLoader(httpClient: HttpClient, settings: GlobalAppSettings) {
  return new TranslationLoader(httpClient, settings);
}

@NgModule({
  imports: [
    ....
    // Translate
    TranslateModule.forChild({
      loader: { provide: TranslateLoader, useFactory: (createTranslateLoader), deps: [HttpClient, GlobalAppSettings] }
    }),
    ....
  ],
  declarations: [
   ....
  ],
  exports: [HomeMenuComponent],
  providers: [
...
  ]
})
export class EDossierContainerModule { }
```

**Comment by luiscla27** [comment] 2018-11-29 17:32
It is an issue,

A couple of days ago i've faced the same issue for another Angular Library ([igniteui](https://github.com/IgniteUI/igniteui-angular/issues/3026)), 

The problem can be solved by removing the `forRoot()` implementation and using the recently introduced `providedIn `property of the `@Injectable` decorator, in short `TranslateModule.forRoot()` will be deprecated.

This would be breaking-change so it requires someone to dedicate at least a full day to migrate the implementation, this is what the [Angular 6 documentation](https://angular.io/guide/singleton-services) says:

> Beginning with Angular 6.0, the preferred way to create a singleton services is to specify on the service that it should be provided in the application root. This is done by setting providedIn to root on the service's @Injectable decorator:

**Comment by katan** [comment] 2018-12-11 09:44
Same issue here using a lazy load modules.

**Comment by miki995** [comment] 2018-12-20 18:59
Same issue with lazy loading, any signs of progress?

**Comment by dmkdfc** [comment] 2019-02-04 17:46
https://github.com/dmkdfc/IonicMultiLanguage.git

**Comment by HDaghash** [comment] 2019-02-20 08:58
any update on this ?

**Comment by HDaghash** [comment] 2019-02-20 09:28
temp solution works for me 

in your shared module import and export like so 


without using forChild or forRoot
```
 imports: [
    TranslateModule
  ],
  exports: [
   TranslateModule
  ], 
```

in you app module import forRoot

```
imports:[
TranslateModule.forRoot({
      loader: {
        provide: TranslateLoader,
        useFactory: createTranslateLoader,
        deps: [HttpClient]
      },
      isolate: true
    })
]
```

this is was cool for me .

**Comment by shairez** [comment] 2019-02-26 00:10
## In case this can help anyone out there- 

I've been struggling with a similar issue.

I had a lazy loaded module that didn't show any translations.
After (a lot) of debugging, I saw that the `TranslateStore` was being created twice. 

At first I thought it was a bug, but after digging into it I saw that the Lazy Loaded module imported a module, which imported a module which had a `TranslateModule.forRoot()` in its imports.

It was hard to trace because it was "hidden" inside of a shared library project.

Anyway, I hope it will save some of you some debugging time, if you're suffering from the same (hidden) cluster fudge 😄

**Comment by subhani1249** [comment] 2019-02-26 12:26
**MainModule.ts**

![image](https://user-images.githubusercontent.com/10893928/53412279-f06a2a80-39ee-11e9-9ce0-96487e95fbbd.png)

**Create one shared module  translateSharedModule.ts**

![image](https://user-images.githubusercontent.com/10893928/53412327-18598e00-39ef-11e9-9e3b-ea120a1ebedf.png)

**appComponent.ts**
import {TranslateService} from '@ngx-translate/core';
 constructor(public translate: TranslateService) {
      translate.setDefaultLang('en');
 
  }

**homeModule.ts   //or any other submodules**
import { TranslateSharedLazyModule } from '../../Common/translateSharedLazyModule';
imports        : [        
        TranslateSharedLazyModule
    ], ..

**Comment by stemda** [comment] 2019-04-25 10:47
My case was:

* Have a global translation file loaded with the main application
* Lazy load several feature modules, each with their own translation files
** Extend the core translations only when needed

I solved my problem by adding an option `extend` , which allows lazy loaded modules to extend the translations for a given language instead of ignoring them, if already present.

If you're interested, you can get it here:

https://github.com/stemda/ngx-translate

Probably not good enough for a PR but maybe it helps some of you...

**Comment by iamruslanbakirov** [comment] 2019-05-09 16:12
Hi all, I trying to use this example, but its not working? Why for lazy module translation dictionary not merged with module forRoot? 

> I wouldn't mind having to create different translateLoader per module, just without using `isolate: true` should work, something along:
> 
> ```
> // app.module.ts
> export function HttpLoaderFactory(http: Http) {
>    return new TranslateHttpLoader(http, './assets/i18n/app/', '.json');
> }
> 
> @NgModule({
>     imports: [
>       TranslateModule.forChild({
>         loader: {
>           provide: TranslateLoader,
>            useFactory: HttpLoaderFactory,
>            deps: [Http]
>         }
>      })
>    ]
> })
> export class AppModule {}
> 
> // in a lazy-loaded page's module
> // pages/home/page.module.ts
> export function HttpLoaderFactory(http: Http) {
>    return new TranslateHttpLoader(http, './assets/i18n/home/', '.json');
> }
> 
> @NgModule({
>     imports: [
>       TranslateModule.forChild({
>         loader: {
>           provide: TranslateLoader,
>            useFactory: HttpLoaderFactory,
>            deps: [Http]
>         }
>      })
>    ]
> })
> export class HomePageModule {}
> ```

**Comment by stemda** [comment] 2019-05-10 07:59
I posted a possible solution for your problem above. If you dont want to check out the fork, just download a patch 

https://github.com/foo/bar/commit/${SHA}.patch

https://github.com/stemda/ngx-translate/commit/f54bc5303124ec35a5e2ab4f51e59cf9920f5cd8.patch

and try it out.

**Comment by iamruslanbakirov** [comment] 2019-05-10 08:34
@stemda omg, nice! I just few minutes already forked for same patch. :)
Are you can create PR for resolve this issue?

**Comment by stemda** [comment] 2019-05-10 13:36
@iamruslanbakirov okay, I just started a pull request. 
btw. I decided against overwriting already present translations within the merge since that could lead to very confusing behaviour. the result would depend on the loading sequence of the modules, which isn't really great I think.

**Comment by Tolitech** [comment] 2019-05-11 13:29
Hello. 

If I understand correctly, with "extend" it will be possible to use a shared.json and a module.json file (by lazy loading module) and the "extend" will not overwrite but make an append with shared.json?

Would be perfect.
I'm really in need of this to better organize the translations and still make GET just the necessary one used in the module (lazy-loading).

Thanks.

**Comment by stemda** [comment] 2019-05-20 08:48
Hey, @Tolitech, sorry for my late response. Yes, that's excactly what the patch does.

**Comment by Tolitech** [comment] 2019-05-20 11:38
@stemda 
thank you.
I'll wait for this feature.

**Comment by iansowinski** [comment] 2019-05-31 12:06
@ocombe what we can do for you to speed up merging @stemda changes?

**Comment by akiik** [comment] 2019-06-27 06:24
Hey!

I'm facing the same issue here and @stemda changes will fix the problem. I'm really looking forward to this PR being merged.

Thank you.

**Comment by pvkrijesh** [comment] 2019-09-18 06:26
> I wrote a article about how to have 1 json file per lazy loaded module without having to write a new Custom Loader etc... it's quiet simple, only the documentation is not clear in fact:
> https://medium.com/@TuiZ/how-to-split-your-i18n-file-per-lazy-loaded-module-with-ngx-translate-3caef57a738f

Hey , Could you please give it a clear documentation. I am using ngrx/store and i need to use ngx-translate in lazy loaded module and other places it should be in module level transalation. 
if you have time please upload a sample example in github

**Comment by Tuizi** [comment] 2019-09-23 16:18
@pvkrijesh a working example updated to Angular 8:
https://github.com/Tuizi/i18n-split-example

**Comment by pvkrijesh** [comment] 2019-09-24 06:23
> @pvkrijesh a working example updated to Angular 8:
> https://github.com/Tuizi/i18n-split-example

Thank you Tuizi ... I cloned the repo and its working fine . But when I tried to use in my application 
It takes only from app/i18n/en.json | app/i18n/fr.json  files. When I moved to other modules it is not even triggering to createTranslateLoader method ... It does not show up any error too..  I hope you can help me out on this...

**Comment by Tolitech** [comment] 2019-09-25 17:52
> 
> 
> @pvkrijesh a working example updated to Angular 8:
> https://github.com/Tuizi/i18n-split-example

@pvkrijesh 
This example does not work exactly.

The problem is not just detaching each module into a new json file.

But if you have a shared json with 10 translations for example, it cannot be used by others and always has to be copied again, which makes using this way bad.

**Comment by Tolitech** [comment] 2019-09-25 17:54
> 
> 
> @pvkrijesh a working example updated to Angular 8:
> https://github.com/Tuizi/i18n-split-example

@Tuizi 

This example does not work exactly.

The problem is not just detaching each module into a new json file.

But if you have a shared json with 10 translations for example, it cannot be used by others and always has to be copied again, which makes using this way bad.

**Comment by kristofdegrave** [comment] 2020-01-20 10:34
Based on the solution @Almar provided, I'm also using the MissingTranslationHandler to determine if additional translations need to be fetched. The parts that I've changed compared to @Almar solution is that I make use of the loader configured inside the translation service. Because a new instance of the TranslationService is created when using the forChild method, this is nicely isolated, the same counts for the missinghandler that is configured.

https://gist.github.com/kristofdegrave/64863e249bbc8768fe33fc666dfa8bf5

**Closed** 2020-02-05 15:27 UTC
Labels: Priority: critical, Type: bug

**Comment by yasskant** [comment] 2020-07-01 11:20
I¡ve developed a lazy loading per module solution through a factory.

1. create a folder assets/i18n/modulexxx for every module
2. add the language json en.json, fr.json..etc in that folder
3. Add the TranslateLoder factory  (e.g shared/i18n/TranslateLoader.ts)

import { TranslateLoader } from '@ngx-translate/core';
import { Observable, from } from 'rxjs';

const appAvailableLanguages = ['ar', 'en', 'es', 'fr'];
const defaultLanguage = 'en';

export class TranslateLoaderFactory {
    static forModule(module: string): any {
        return class LazyTranslateLoader implements TranslateLoader {
            getTranslation(lang: string): Observable<any> {
                if (!appAvailableLanguages.includes(lang)) {
                    return from(import(`../../../assets/i18n/${module}/${defaultLanguage}.json`));
                }
                return from(import(`../../../assets/i18n/${module}/${lang}.json`));
            }
        }
    }
}

4. Use in in your root and lazy loaded modules as:
 -  root:
  TranslateModule.forRoot({
            loader: {
                provide: TranslateLoader,
                useClass: TranslateLoaderFactory.forModule('main'),
                deps: [HttpClient]
            }
        }),

 - lazy loaded module:
  TranslateModule.forChild({
            loader: {
                provide: TranslateLoader,
                useClass: TranslateLoaderFactory.forModule('main'),
                deps: [HttpClient]
            }
        }),

Hope that helps

**Comment by jlopezjuy** [comment] 2020-07-04 12:31
> I¡ve developed a lazy loading per module solution through a factory.
> 
> 1. create a folder assets/i18n/modulexxx for every module
> 2. add the language json en.json, fr.json..etc in that folder and the shared ones in assets/i18n
> 3. Add the TranslateLoder factory  (e.g shared/i18n/TranslateLoader.ts)
> 
> ```ts
> import { TranslateLoader } from '@ngx-translate/core';
> import { Observable, from, merge } from 'rxjs';
> 
> const appAvailableLanguages = ['ar', 'en', 'es', 'fr'];
> const defaultLanguage = 'en';
> 
> export class TranslateLoaderFactory {
>     static forModule(module: string): any {
>         return class LazyTranslateLoader implements TranslateLoader {
>             getTranslation(lang: string): Observable<any> {
>                 if (!appAvailableLanguages.includes(lang)) {
>                     return merge(
>                         from(import(`../../../assets/i18n/${defaultLanguage}.json`)),
>                         from(import(`../../../assets/i18n/${module}/${defaultLanguage}.json`))
>                     );
>                 }
>                 return merge(
>                     from(import(`../../../assets/i18n/${lang}.json`)),
>                     from(import(`../../../assets/i18n/${module}/${lang}.json`))
>                 );
>             }
>         }
>     }
> }
> ```
> 
> 1. Use in in your root and lazy loaded modules as:
> 
> * root:
> 
> ```ts
> TranslateModule.forRoot({
>           loader: {
>               provide: TranslateLoader,
>               useClass: TranslateLoaderFactory.forModule('main'),
>               deps: [HttpClient]
>           }
>       }),
> ```
> 
> * lazy loaded module:
> 
> ```ts
> TranslateModule.forChild({
>           loader: {
>               provide: TranslateLoader,
>               useClass: TranslateLoaderFactory.forModule('mymodule'),
>               deps: [HttpClient]
>           }
>       }),
> ```
> 
> Hope that helps

Hi, could you share a github project working? i have testest but not work.

**Comment by iansowinski** [comment] 2020-07-05 06:17
Either way it could be nice to merge this PR. I had to fork this repo just to have this issue resolved in the project I'm in...

**Comment by appstore-redphoenix** [comment] 2020-09-03 12:58
one more workaround to trigger language change globally including lazy modules

```
  export class SharedModule {
    constructor(
      private languageService: LanguageService,
      private translateService: TranslateService
    ) {
      this.languageService.language.subscribe((lang) => {
        this.translateService.use(lang);
      });
    }
  }

```

**Comment by Totot0** [comment] 2020-11-15 16:10
I am the same problem. Isolet true not working for me. Do you have a solution ?
I use Angular 9

**Comment by isamely1990** [comment] 2021-04-29 14:13
After a few days searching, reading and trying other solutions, I found that in my case, my team and I, we had a bad implementation of lazy loading in the routing, we had the component declared in the route, and in the pages module, causing that we only receive the translation in just 1 module instead of all modules where we used TranslateModule.forChild

So maybe works to check if the lazy load is ok in your project, the component mus be declare only in each anycomponent-module.ts

`path: 'clients',
    // component: ClientsComponent,  REMOVED 
    loadChildren: () => import('./clients/clients.module').then(m => m.ClientsModule)`

**Comment by brianmriley** [comment] 2021-05-10 21:14
@Juusmann's solution works for me as well. To be extremely specific and to add clarity to anyone still wondering how it all fits together, I have the following setup (using abbreviated module definitions):

**AppModule**

```
...
// AoT requires an exported function for factories.
export function HttpLoaderFactory(http: HttpClient): TranslateHttpLoader {
    return new TranslateHttpLoader(http, './assets/i18n/', '.json');
}

...

imports: [
   ...
   // NOTE: Normally we'd stick TranslateModule in `CoreModule` but the ability to lazy load
   // module translations and extend the main one only works if you set it up in the root `AppModule`.
   // Use the TranslateModule's config param "isolate: false" to allow child, lazy loaded modules to 
   // extend the parent or root module's loaded translations.
   TranslateModule.forRoot({
        defaultLanguage: 'en',
        loader: {
            provide: TranslateLoader,
            useFactory: HttpLoaderFactory,
            deps: [HttpClient]
        },
        isolate: false
    }),
]
```

**SharedModule**

```
@NgModule({
    declarations: DECLARATIONS,
    imports: [
        ...MODULES,
        ...TranslateModule
    ],
    exports: [
        ...MODULES,
        ...TranslateModule
        ...DECLARATIONS,
    ]
})
export class SharedModule {
}
```

**LazyLoadedModule**

```
...
// AoT requires an exported function for factories.
export function HttpLoaderFactory(http: HttpClient): TranslateHttpLoader {
    return new TranslateHttpLoader(http, './assets/i18n/'lazy-load, '.json');
}

...

imports: [
   ...
   // Use the TranslateModule's config param "extend: true" to extend the parent or root module's
   // loaded translations.
   TranslateModule.forChild({
        defaultLanguage: 'en',
        loader: {
            provide: TranslateLoader,
            useFactory: HttpLoaderFactory,
            deps: [HttpClient]
        },
        extend: true
    }),
]
export class LazyLoadedModule {
    constructor(protected translateService: TranslateService) {
        const currentLang = translateService.currentLang;
        translateService.currentLang = '';
        translateService.use(currentLang);
    }
}
```

**Key Points**

* Use the `TranslateModule's` method `forRoot()` with config param `isolate: false` in `AppModule` to allow child, lazy loaded modules to extend the parent or root module's loaded translations.
* Use the `TranslateModule's` method `forChild()` with config param `extend: true` in `LazyLoadedModule` to extend the parent or root module's loaded translations.
* **DO NOT** attempt to move the `TranslateModule` setup and configuration from `AppModule` to a `CoreModule` as it won't allow the root translations  and only works when setup directly in `AppModule`.
* Force `TranslateModule` to load the `LazyLoadedModule's` child translations by setting the locale on the `TranslateService` in its constructor.

**Comment by docwhite** [comment] 2021-07-15 09:26
Still having this issue. I can't understand why this issue is closed. The `extend` option does not seem to respect the parent module translations. Does anyone have a StackBlitz showing the `extend` doing what it's supposed to do for lazy loaded modules that load .json files from another subfolder?

**Comment by niroshank** [comment] 2021-08-14 18:46
LazyLoadedModule - isolated : true -> Main translations file is loaded
LazyLoadedModule - isolated : false -> Feature translations file is loaded
I also have added the translateService in its constructor.

**Comment by KevinKallin** [comment] 2023-10-02 13:20
@brianmriley 
OMG thank you!

Me and another colleague have worked a couple of days trying to solve this and your solution did work perfectly fine! :)

**Comment by sdedieu** [comment] 2024-05-20 15:30
Hey @brianmriley ! 
I did your instructions but end up with `translateService.currentLang` as `undefined` (instead of the chosen language) in the lazy loaded Module contructor.
Any idea why ?

**Comment by rbalet** [comment] 2025-07-30 06:40
Fixed in the latest [v17 release](https://github.com/ngx-translate/core/releases/tag/v17.0.0) with the new isolated & extended logic

-> https://ngx-translate.org/reference/concepts/#configuration
