### ISSUE TITLE
Char ":" in parameter for label create error

### ISSUE THREAD

**Issue by breslavsky** [ngx-translate/core#569] opened 2017-06-15 20:18 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**

p [innerHTML]="'LABEL' | translate: {date: '15.06.2017, 22:40 Uhr'}"

In console:
Wrong parameter in TranslatePipe. Expected a valid Object, received: 
{date: '15.06.2017, 22:40 Uhr'}

The problem with ":" char. 
If remove ":" {date: '15.06.2017, 22:40 Uhr'} -> {date: '15.06.2017, 2240 Uhr'}
Everything works.

**Expected/desired behavior**

Char ":" must not create fail.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via https://plnkr.co or similar. You can use this template as a starting point: http://plnkr.co/edit/tpl:01UjWY3TKfP6pgwXKuEa

**What is the expected behavior?**

Char ":" must not create fail.

**What is the motivation / use case for changing the behavior?**

Use char ":" in translation parameter.

**Please tell us about your environment:**

* **ngx-translate version:** x.x.x

3.1.2

* **Angular version:** 2.x.x
 
4.0.0

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome Version 58.0.3029.110 (64-bit)

**Comment by CodeAndWeb** [comment] 2018-03-28 21:12
Could not reproduce the issue in the current version.

Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.
I am closing the issue for now - you can re-open it if the issue still persists or you still need help.

**Closed by CodeAndWeb** 2018-03-28 21:12 UTC

**Comment by tibistibi** [comment] 2018-06-22 15:05
i came across the same problem, is it back again?

**Comment by Emilieczq** [comment] 2018-08-06 07:18
@CodeAndWeb I have the same problem.

**Comment by Writtscher** [comment] 2018-08-13 12:50
Same here:

```
JhiTranslateComponent.html:1 ERROR SyntaxError: Wrong parameter in TranslatePipe. Expected a valid Object, received: {name: 'Test [TEXT][XXX:ZZZ]'}
    at TranslatePipe.transform (translate.pipe.js?ebce:53)
```

**Comment by stephanegg** [comment] 2018-08-18 23:52
Same error with ":" char. @CodeAndWeb could you please re open the issue? I am using Angular 6.0.9
 and ngx-translate/core 10.0.2

**Comment by MartinWeb** [comment] 2018-09-13 08:50
Had the same problem and i found a workaround until the issue is fixed.
Replacing the ":" character that creates the issue with his ASCII representation `&#58;`

So here's the small code that make me able to use the : character
`.replace("\:","&#58;")`
