### ISSUE TITLE
Dictionary called twice on init

### ISSUE THREAD

**Issue by maximelafarie** [ngx-translate/core#462] opened 2017-03-08 14:49 UTC
**I'm submitting a ...**  (check one with "x")
```
[x] bug report => check the FAQ and search github for a similar issue or PR before submitting
[ ] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
If I follow the readme step 2, with the following code : 
```
constructor(translate: TranslateService) {
    translate.setDefaultLang('fr');
    translate.use('fr');
}
```

Then in the dev console (network tab), we can see the dictionary is called twice : 
![image](https://cloud.githubusercontent.com/assets/5319267/23708233/8b85ea7a-0415-11e7-9999-4aa771c8187a.png)

**Expected/desired behavior**

If I comment the last line : 
```
constructor(translate: TranslateService) {
    translate.setDefaultLang('fr');
    //translate.use('fr');
}
```
The dictionary is called only one time :
![image](https://cloud.githubusercontent.com/assets/5319267/23708322/dae13dea-0415-11e7-8f53-ae0021e5a712.png)

**Reproduction of the problem**
Follow the 2nd step of the readme.

**What is the expected behavior?**
Make a single call if the dictionary already loaded.

**What is the motivation / use case for changing the behavior?**
It could be painful if the dictionary is big.

**Please tell us about your environment:**
Angular2 (CLI) / Webpack

* **ngx-translate version:** 6.0.0

* **Angular version:** 2.4.0

* **Browser:** [Chrome 56]

**Comment by ocombe** [comment] 2017-03-08 14:51
Hello, thanks for the report but I'm closing it because it is a duplicate of #397

**Closed by ocombe** 2017-03-08 14:51 UTC
