### ISSUE TITLE
Runtime Error ctorParameters.map is not a function

### ISSUE THREAD

**Issue by ernaneluis** [ngx-translate/core#376] opened 2016-12-27 01:07 UTC
**I'm submitting a**
```
[ ] bug report => check the FAQ and search github for a similar issue or PR before submitting
[x] support request => check the FAQ and search github for a similar issue before submitting
[ ] feature request
```

**Current behavior**
I'm trying to use this component with ionic 2 but is not working, I'm getting this error:
`"Runtime Error ctorParameters.map is not a function"`

**Stack**
```
TypeError: ctorParameters.map is not a function
    at ReflectionCapabilities.parameters (/Users/ernaneluis/Developer/schild/SchildApp/node_modules/@angular/core/src/reflection/reflection_capabilities.js:61:45)
    at Reflector.parameters (/Users/ernaneluis/Developer/schild/SchildApp/node_modules/@angular/core/src/reflection/reflector.js:29:44)
    at CompileMetadataResolver.getDependenciesMetadata (/Users/ernaneluis/Developer/schild/SchildApp/node_modules/@angular/compiler/src/metadata_resolver.js:449:54)
    at CompileMetadataResolver.getTypeMetadata (/Users/ernaneluis/Developer/schild/SchildApp/node_modules/@angular/compiler/src/metadata_resolver.js:414:26)
    at eval (/Users/ernaneluis/Developer/schild/SchildApp/node_modules/@angular/compiler/src/metadata_resolver.js:557:41)
    at Array.forEach (native)
    at CompileMetadataResolver.getProvidersMetadata (/Users/ernaneluis/Developer/schild/SchildApp/node_modules/@angular/compiler/src/metadata_resolver.js:537:19)
    at eval (/Users/ernaneluis/Developer/schild/SchildApp/node_modules/@angular/compiler/src/metadata_resolver.js:235:71)
    at Array.forEach (native)
    at CompileMetadataResolver.getNgModuleMetadata (/Users/ernaneluis/Developer/schild/SchildApp/node_modules/@angular/compiler/src/metadata_resolver.js:226:44)
```

**Reproduction of the problem**
at **app.module.ts**
in @NgModule
when I try to add this 

`TranslateModule.forRoot()`
or

```
  TranslateModule.forRoot({
        provide: TranslateLoader,
        useFactory: (createTranslateLoader),
        deps: [Http]
      })
```

in **imports** then I get that error.

**My environment:**

Ionic Framework: 2.0.0-rc.3
Ionic Native: 2.2.3
Ionic App Scripts: 0.0.46
Angular Core: 2.1.1
Angular Compiler CLI: 2.1.1
Node: 7.2.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 OPR/42.0.2393.94

**Comment by nitinkothwal** [comment] 2016-12-27 12:30
I am also stuck with this issue.

**Comment by romrossir** [comment] 2016-12-29 10:41
Hello,
I think you have to upgrade your dependencies to use ng2-translate 5.0.0.

My environment is working with:
Ionic Framework: 2.0.0-rc.4
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1

**Comment by ernaneluis** [comment] 2016-12-29 18:22
**I'm still getting the same error :( , even with this env:**

```
Ionic Framework: 2.0.0-rc.4
Ionic Native: 2.2.11
Ionic App Scripts: 0.0.48
Angular Core: 2.2.1
Angular Compiler CLI: 2.2.1
Node: 7.2.0
OS Platform: macOS Sierra
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.87 Safari/537.36 OPR/42.0.2393.94
```

**Comment by ernaneluis** [comment] 2016-12-29 20:53
I fix this issue by running:
`npm install `

I have forgotten to do this.

**Comment by as02700** [comment] 2017-01-10 01:25
I found it in compiled code { TranslateModule.ctorParameters = function () { return []; }; }, and i compare to @ngrx/store { StoreModule.ctorParameters = []; }.

**Comment by flintcreativestudio** [comment] 2017-01-15 12:36
This is a outdated angularJS issue, I had it when I was using an older version of AngularJS, but updating to the latest version made some other libraries fail, so I had to find a sweet spot.
For me, that was AngularJS version 2.2.1

You can update your package.json as so, so running npm install will install the required libraries.

> "@angular/common": "~2.2.1",
    "@angular/compiler": "~2.2.1",
    "@angular/core": "~2.2.1",
    "@angular/forms": "~2.2.1",
    "@angular/http": "~2.2.1",
    "@angular/platform-browser": "~2.2.1",
    "@angular/platform-browser-dynamic": "~2.2.1",
    "@angular/router": "~3.1.0",

**Comment by azanebrain** [comment] 2017-01-21 04:55
I've found that this issue is caused by any number of packages expecting the version of Angular Core to be different than what is actually installed.

I was able to figure out the cause of this issue by looking at the error report from ng build:

`npm WARN @angular/platform-server@2.4.4 requires a peer of @angular/core@2.4.4 but none was installed.`

This helped me realize that one of my packages expected Angular to be at v2.4.4, but I'm using v2.0.1. I updated my package.json to have both packages set to my core version like this:

`"dependencies": {
    "@angular/core": "2.0.1",
    "@angular/platform-server": "2.0.1",
}`

Your issue might not be with @angular/platform-server, but I hope this helps debug it

**Comment by ocombe** [comment] 2017-02-07 16:57
Closing this, let me know if you need it to be reopened.

**Closed by ocombe** 2017-02-07 16:57 UTC
