### ISSUE TITLE
[suggestion] add language direction 

### ISSUE THREAD

**Issue by AsimNet** [ngx-translate/core#405] opened 2017-01-25 13:34 UTC
Hello,

thanks for your effort guys..

I'm currently trying to support RTL languages and i'm using this plugin. Is there a method to get the direction of the selected language (RTL OR LTR)?. I suggest to pass a parameter with selected language that determine the direction, so we can use it to update the UI.

how we update the UI?, execute this code inside app.component.ts constructor:
`this.platform.setDir('rtl', true);`

thanks

**Comment by ocombe** [comment] 2018-05-08 12:43
Closing this issue because it's a duplicate of https://github.com/ngx-translate/core/issues/374

**Closed by ocombe** 2018-05-08 12:43 UTC
Labels: Status: duplicate
