### ISSUE TITLE
Unexpected token import

### ISSUE THREAD

**Issue by iTwangcj** [ngx-translate/core#681] opened 2017-09-27 11:06 UTC
> node dist/server

/Users/wangchengjun/www/yooli/mock/universal-starter/angular-mock/node_modules/@ngx-translate/core/src/translate.loader.js:11
import { Observable } from "rxjs/Observable";
^^^^^^
SyntaxError: Unexpected token import
    at Object.exports.runInThisContext (vm.js:76:16)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)

environment:

node: v6.10.0
os: linux x64
angular/cli: "^1.3.0",
angular/compiler-cli: "^4.2.4",
angular/language-service: "^4.2.4",
types/node: "^8.0.30",
angular/animations: "^4.2.4",
angular/common: "^4.2.4",
angular/compiler: "^4.2.4",
angular/core: "^4.2.4",
angular/forms: "^4.2.4",
angular/http: "^4.2.4",
angular/platform-browser: "^4.2.4",
angular/platform-browser-dynamic: "^4.2.4",
angular/platform-server: "^4.3.6",
angular/router: "^4.2.4",
nguniversal/express-engine: "^1.0.0-beta.3",
nguniversal/module-map-ngfactory-loader: "^1.0.0-beta.3",
ngx-translate/core: "^8.0.0",
ngx-translate/http-loader: "^2.0.0",

**Comment by qubiack** [comment] 2017-10-19 19:24
I have exactly the same error. 

It's appear when I add Translate.Module.forRoot() in my app.module.ts

**Comment by DenisVuyka** [comment] 2018-02-20 20:13
Having similar problem, but for the "translate.store"
```
<...>/node_modules/@ngx-translate/core/src/translate.store.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { EventEmitter } from "@angular/core";
```

**Comment by CodeAndWeb** [comment] 2018-03-28 21:17
Could not reproduce the issue in the current version.

Sorry for not answering the issue for such a long time.
We try to do better in the future, promised.
I am closing the issue for now - you can re-open it if the issue still persists or you still need help.

**Closed by CodeAndWeb** 2018-03-28 21:17 UTC
