### ISSUE TITLE
ngFor on traslation 

### ISSUE THREAD

**Issue by Montellanos** [ngx-translate/core#424] opened 2017-02-09 01:10 UTC
I'm a problem with ng2 translate

i have two files of traduction
es.json and en.json
the content
es.json
```json
{"shell" : [{"link": "/home", "name":"inicio"},{"link":"/setting", "name":"configuraciones"}]}
```
en.json
```json
{"shell" : [{"link": "/home", "name":"home"},{"link":"/setting", "name":"setings"}]}
```

the problem is in the template, i find extract and show the shell content in the view with ngFor but not work

and not show the data in the language selected

**Comment by martinop** [comment] 2017-02-09 12:16
You want to translate the path of route??

**Comment by SamVerschueren** [comment] 2017-02-09 12:36
I think what you're trying to do is not a good idea. Why not just do it like this?

```json
{
    "nav": {
        "home": "inicio",
        "settings": "configuraciones"
    }
}
```

```html
<nav>
    <ul>
        <li><a [routerLink]="/home">{{'nav.home' | translate}}</a></li>
        <li><a [routerLink]="/setting">{{'nav.settings' | translate}}</a></li>
    </ul>
</nav>
```

This (to me) looks much much cleaner then what you're trying to do. I always think like this, it should be able to send the translation file to a translator with no knowledge of the framework or whatsoever. Also, this way all the translations are decoupled from the implementation. If tomorrow you decide that the route should be named `/settings` instead of `/setting`, you will have to replace all of those in every translation file you have. That's definitely not what you want.

**Comment by ocombe** [comment] 2017-02-09 13:12
Mixing data and translations is not a good idea.
I've done it in a project, and I can tell you that it ends up being a problem. Other devs didn't understand what I was doing, they changed keys without thinking that it would make things fail. Or they forgot to change it in all the translations (because it worked for them in english).
Also it means that your code becomes very tightly tied to the library, if there is a breaking change for some reason, you won't be able to update.
And then the problem is that your app won't be updated until after init (when the translations load), which will probably trigger a weird visual effect, or some delay in the view.
When you have no choice (because the data is on the server) then it's ok, but in this case you already know the structure in the front end, it's just the text that changes.

**Comment by SamVerschueren** [comment] 2017-02-15 14:14
Going to close this. Let us know if you still want to discuss this.

**Closed by SamVerschueren** 2017-02-15 14:14 UTC
